version: "3"
services:
  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password123
      - POSTGRES_DB=datum_vitae_development
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "5000:5000"
    depends_on:
      - db
volumes:
  db-data:
